server:
  port: 8001

spring:
  application:
    name: cloud-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations:
  type-aliases-package:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: payment01
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 90


